### ISSUE TITLE
Ruby Toolbox notice

### ISSUE THREAD

**Issue by DanL12186** [learn-co-curriculum/rails-how-to-find-gems-readme#4]
Apparently the server died and a lot of data was lost. This message shows up when visiting any gem (e.g. https://www.ruby-toolbox.com/categories/blog_engines): 

Bad news. The server hosting The Ruby Toolbox went bust on the evening of June 7th. While I do have backups, the state of the original source code is in a very outdated state so I currently don't feel it makes sense to try and get it running again.

I've been meaning and promising to finally create an open source version of the site for years now, but due to lack of time so far I failed to execute on that promise. I'm taking the server failure as the final, gentle push to get this whole endeavour going.

For the time being, here is a very stripped down version of the Ruby Toolbox's contents. Please bear with me while I set up a place to discuss the future of the Ruby Toolbox. Watch this space or check out my Twitter account for announcements on that.

- Christoph

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback.

The Ruby Toolbox has since received funding and is back up full-time with the new and improved (and open source) application: https://www.ruby-toolbox.com/

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
